export const DISTRICTS = [
  "Kathmandu",
  "Lalitpur",
  "Bhaktapur",
  "Kaski",
  "Chitwan",
  "Rupandehi",
  "Morang",
  "Sunsari",
  "Jhapa",
  "Kailali",
  "Banke",
  "Bara",
  "Parsa",
  "Makwanpur",
  "Dhading",
  "Nuwakot",
  "Sindhuli",
  "Kavrepalanchok",
  "Sindhupalchok",
  "Ramechhap",
  "Dolakha",
  "Solukhumbu",
  "Okhaldhunga",
  "Khotang",
  "Bhojpur",
  "Terhathum",
  "Taplejung",
  "Panchthar",
  "Ilam",
  "Dhankuta",
  "Sankhuwasabha",
  "Udayapur",
  "Saptari",
  "Siraha",
  "Dhanusha",
  "Mahottari",
  "Sarlahi",
  "Rautahat",
  "Bara",
  "Parsa",
  "Rukum East",
  "Rukum West",
  "Rolpa",
  "Salyan",
  "Dang",
  "Pyuthan",
  "Arghakhanchi",
  "Palpa",
  "Gulmi",
  "Kapilvastu",
  "Nawalpur",
  "Parasi",
  "Rupandehi",
  "Syangja",
  "Tanahun",
  "Lamjung",
  "Gorkha",
  "Manang",
  "Mustang",
  "Myagdi",
  "Baglung",
  "Parbat",
  "Surkhet",
  "Dailekh",
  "Jajarkot",
  "Dolpa",
  "Mugu",
  "Humla",
  "Kalikot",
  "Jumla",
  "Bajura",
  "Bajhang",
  "Achham",
  "Doti",
  "Baitadi",
  "Darchula",
  "Dadeldhura",
  "Kanchanpur",
];

export const SKILLS = [
  "React.js",
  "Next.js",
  "Vue.js",
  "Angular",
  "Node.js",
  "Express.js",
  "Python",
  "Django",
  "Flask",
  "PHP",
  "Laravel",
  "WordPress",
  "Java",
  "Spring Boot",
  "Flutter",
  "React Native",
  "iOS Development",
  "Android Development",
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "Logo Design",
  "Branding",
  "Video Editing",
  "Motion Graphics",
  "After Effects",
  "Premiere Pro",
  "Content Writing",
  "Copywriting",
  "Blog Writing",
  "SEO Writing",
  "Translation (Nepali-English)",
  "Digital Marketing",
  "Social Media Marketing",
  "Facebook Ads",
  "Google Ads",
  "SEO",
  "Email Marketing",
  "Photography",
  "Product Photography",
  "Data Entry",
  "Excel/Spreadsheets",
  "Virtual Assistant",
  "Customer Support",
  "TypeScript",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Firebase",
  "AWS",
  "Docker",
];

export const CATEGORIES = [
  { value: "web-development", label: "Web Development", icon: "Globe" },
  { value: "mobile-app", label: "Mobile App", icon: "Smartphone" },
  { value: "graphic-design", label: "Graphic Design", icon: "Palette" },
  { value: "content-writing", label: "Content Writing", icon: "PenTool" },
  { value: "video-editing", label: "Video Editing", icon: "Video" },
  { value: "digital-marketing", label: "Digital Marketing", icon: "TrendingUp" },
  { value: "data-entry", label: "Data Entry", icon: "Database" },
  { value: "photography", label: "Photography", icon: "Camera" },
  { value: "translation", label: "Translation", icon: "Languages" },
  { value: "seo", label: "SEO", icon: "Search" },
  { value: "social-media", label: "Social Media", icon: "Share2" },
  { value: "other", label: "Other", icon: "MoreHorizontal" },
];

export const AVAILABILITY_OPTIONS = [
  { value: "available", label: "Available" },
  { value: "busy", label: "Busy" },
  { value: "unavailable", label: "Unavailable" },
];

export const PAYMENT_METHODS = [
  { value: "khalti", label: "Khalti", color: "#5C2D91" },
  { value: "esewa", label: "eSewa", color: "#60BB46" },
  { value: "bank", label: "Bank Transfer", color: "#1E40AF" },
];

export const PROJECT_STATUSES = [
  { value: "open", label: "Open", color: "bg-blue-100 text-blue-800" },
  { value: "in-progress", label: "In Progress", color: "bg-yellow-100 text-yellow-800" },
  { value: "completed", label: "Completed", color: "bg-green-100 text-green-800" },
  { value: "cancelled", label: "Cancelled", color: "bg-red-100 text-red-800" },
  { value: "disputed", label: "Disputed", color: "bg-orange-100 text-orange-800" },
];
